"""
Sibling-server orchestration endpoints (Level 2 & 3).

Routes image-generation and voice/TTS requests to the dedicated sibling servers
(Open Fantasia :8765, Olly Voice :8766) and exposes a setup/status helper so the
UI can show install instructions when a sibling is not running.
"""

from typing import Any, Dict

import asyncio

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from classify import check_services
from siblings import (
    SIBLING_INSTALL,
    SiblingUnavailable,
    proxy_json,
    sibling_unavailable_detail,
    get_sibling_config,
)

router = APIRouter(tags=["siblings"])


class GenerateRequest(BaseModel):
    model: str
    prompt: str
    # Extra image-generation options are forwarded as-is.
    extra: Dict[str, Any] = {}


class TTSRequest(BaseModel):
    model: str
    text: str
    # Extra TTS options are forwarded as-is.
    extra: Dict[str, Any] = {}


@router.post(
    "/generate",
    summary="Generate an image via Open Fantasia",
    description=(
        "Routes an image-generation request to the Open Fantasia sibling server "
        "(:8765). The JSON body is forwarded as-is; the sibling's response is "
        "returned unchanged. Returns 503 with install instructions when Open "
        "Fantasia is not running."
    ),
    responses={
        200: {"description": "Image generated by Open Fantasia."},
        503: {"description": "Open Fantasia not running — install prompt."},
    },
)
async def generate_image(payload: Dict[str, Any]):
    cfg = get_sibling_config("imagegen")
    if not cfg:
        raise HTTPException(status_code=400, detail="Unknown imagegen service.")
    url = cfg["url"].rstrip("/") + "/generate"
    try:
        return await _to_thread_proxy(url, payload)
    except SiblingUnavailable as e:
        detail = sibling_unavailable_detail(cfg["service"], cfg["url"], cfg["install"])
        raise HTTPException(status_code=503, detail=detail) from e


@router.post(
    "/tts",
    summary="Synthesize speech via Olly Voice",
    description=(
        "Routes a text-to-speech request to the Olly Voice sibling server (:8766). "
        "The JSON body is forwarded as-is; the sibling's response is returned "
        "unchanged. Returns 503 with install instructions when Olly Voice is not "
        "running."
    ),
    responses={
        200: {"description": "Speech synthesized by Olly Voice."},
        503: {"description": "Olly Voice not running — install prompt."},
    },
)
async def synthesize_speech(payload: Dict[str, Any]):
    cfg = get_sibling_config("voice")
    if not cfg:
        raise HTTPException(status_code=400, detail="Unknown voice service.")
    url = cfg["url"].rstrip("/") + "/tts"
    try:
        return await _to_thread_proxy(url, payload)
    except SiblingUnavailable as e:
        detail = sibling_unavailable_detail(cfg["service"], cfg["url"], cfg["install"])
        raise HTTPException(status_code=503, detail=detail) from e


@router.get(
    "/services",
    summary="Sibling-server status + install instructions",
    description=(
        "Returns availability and install commands for each sibling server "
        "(Open Fantasia :8765, Olly Voice :8766). Used by the UI to show status "
        "and a setup wizard."
    ),
    tags=["siblings"],
)
async def services():
    result = check_services()
    # Enrich with install instructions
    for modality, info in result.items():
        info["install"] = SIBLING_INSTALL.get(modality, "")
    return result


async def _to_thread_proxy(url: str, payload: Dict[str, Any]):
    """Run the blocking proxy_json in a thread so the event loop stays free."""
    return await asyncio.to_thread(proxy_json, url, payload)
