"""
Sibling-server orchestration endpoints (Level 2 & 3).

Routes image-generation and voice/TTS requests to the dedicated sibling servers
(Open Fantasia :8765, Olly Voice :8766) and exposes a setup/status helper so the
UI can show install instructions when a sibling is not running.

Sibling contracts (confirmed against the running services):
- Open Fantasia  POST /generate — JSON body -> raw image bytes (image/png)
- Olly Voice    POST /tts      — multipart/form-data (text=...) -> wav bytes
"""

from typing import Any, Dict

import asyncio

from fastapi import APIRouter, HTTPException, Response

from classify import check_services
from siblings import (
    SIBLING_INSTALL,
    SiblingUnavailable,
    proxy_binary,
    proxy_multipart,
    sibling_unavailable_detail,
    get_sibling_config,
)

router = APIRouter(tags=["siblings"])


@router.post(
    "/generate",
    summary="Generate an image via Open Fantasia",
    description=(
        "Routes an image-generation request to the Open Fantasia sibling server "
        "(:8765). The JSON body is forwarded as-is. Returns the raw image bytes "
        "(image/png) with the `X-Saved-Paths` header. Returns 503 with install "
        "instructions when Open Fantasia is not running."
    ),
    responses={
        200: {"description": "Image generated by Open Fantasia (raw bytes)."},
        503: {"description": "Open Fantasia not running — install prompt."},
    },
)
async def generate_image(payload: Dict[str, Any]):
    cfg = get_sibling_config("imagegen")
    if not cfg:
        raise HTTPException(status_code=400, detail="Unknown imagegen service.")
    url = cfg["url"].rstrip("/") + "/generate"
    try:
        body, headers = await asyncio.to_thread(proxy_binary, url, payload)
    except SiblingUnavailable as e:
        detail = sibling_unavailable_detail(cfg["service"], cfg["url"], cfg["install"])
        raise HTTPException(status_code=503, detail=detail) from e

    media_type = headers.get("content-type", "image/png")
    saved = headers.get("x-saved-paths")
    resp = Response(content=body, media_type=media_type)
    if saved:
        resp.headers["X-Saved-Paths"] = saved
    return resp


@router.post(
    "/tts",
    summary="Synthesize speech via Olly Voice",
    description=(
        "Routes a text-to-speech request to the Olly Voice sibling server (:8766). "
        "The JSON body's `text` field is sent as multipart/form-data; the sibling's "
        "wav stream is returned as raw bytes. Returns 503 with install instructions "
        "when Olly Voice is not running."
    ),
    responses={
        200: {"description": "Speech synthesized by Olly Voice (wav bytes)."},
        503: {"description": "Olly Voice not running — install prompt."},
    },
)
async def synthesize_speech(payload: Dict[str, Any]):
    cfg = get_sibling_config("voice")
    if not cfg:
        raise HTTPException(status_code=400, detail="Unknown voice service.")
    text = payload.get("text") or payload.get("prompt")
    if not text:
        raise HTTPException(status_code=400, detail="Missing 'text' field for TTS.")
    fields: Dict[str, Any] = {"text": text}
    if payload.get("model"):
        fields["model"] = payload["model"]
    url = cfg["url"].rstrip("/") + "/tts"
    try:
        body, headers = await asyncio.to_thread(proxy_multipart, url, fields)
    except SiblingUnavailable as e:
        detail = sibling_unavailable_detail(cfg["service"], cfg["url"], cfg["install"])
        raise HTTPException(status_code=503, detail=detail) from e

    media_type = headers.get("content-type", "audio/wav")
    return Response(content=body, media_type=media_type)


@router.get(
    "/services",
    summary="Sibling-server status + install instructions",
    description=(
        "Returns availability and install commands for each sibling server "
        "(Open Fantasia :8765, Olly Voice :8766). Used by the UI to show status "
        "and a setup wizard."
    ),
    tags=["siblings"],
)
async def services():
    result = check_services()
    # Enrich with install instructions
    for modality, info in result.items():
        info["install"] = SIBLING_INSTALL.get(modality, "")
    return result
